name: Subsites
description: Applies all the Subsites recipes.
type: Site
recipes:
  - core/recipes/basic_block_type
  - core/recipes/content_search
  - core/recipes/core_recommended_performance
  - core/recipes/core_recommended_maintenance
  - core/recipes/core_recommended_front_end_theme
  - core/recipes/user_picture
  - core/recipes/basic_shortcuts
  # Provides a fallback text format which is available to all users.
  - core/recipes/restricted_html_format
  # Not in Standard...
  - core/recipes/remote_video_media_type
  - subsites_admin_theme
install:
  - metatag
  - menu_link_content
  - project_browser
  - redirect
  - uli_custom_workflow
  # The rest of these are in Standard.
  - help
  - history
  - config
  - contextual
  - menu_link_content
  - datetime
  - menu_ui
  - options
  - shortcut
  - toolbar
  - field_ui
  - views_ui
config:
  import:
    help:
      - search.page.help_search
    image:
      - image.style.large
      - image.style.thumbnail
    metatag: '*'
    node:
      - views.view.archive
      - views.view.content
      - views.view.content_recent
      - views.view.frontpage
      - views.view.glossary
    olivero:
      - block.block.olivero_help
      - block.block.olivero_search_form_narrow
      - block.block.olivero_search_form_wide
      - block.block.olivero_syndicate
    shortcut:
      - shortcut.set.default
    user:
      - core.entity_view_mode.user.compact
      - search.page.user_search
      - views.view.user_admin_people
      - views.view.who_s_new
      - views.view.who_s_online
  actions:
    olivero.settings:
      simple_config_update:
        base_primary_color: '#0a205a'
    project_browser.admin_settings:
      simple_config_update:
        enabled_sources:
          - drupalorg_mockapi
          - local_recipes
    system.site:
      simple_config_update:
        name: 'Subsites'
        page.front: '/node'
    user.role.content_editor:
      grantPermissionsForEachMediaType:
        - 'create %bundle media'
        - 'delete any %bundle media'
        - 'edit any %bundle media'
      grantPermissionsForEachNodeType:
        - 'clone %bundle content'
        - 'create %bundle content'
        - 'delete %bundle revisions'
        - 'delete any %bundle content'
        - 'edit any %bundle content'
    node.settings:
      simple_config_update:
        # @todo Remove `langcode` once https://drupal.org/i/3427564 lands.
        langcode: en
        use_admin_theme: true
    user.role.authenticated:
      grantPermissions:
        - 'access help pages'
        - 'access shortcuts'
        - 'access user profiles'
        - 'delete own files'
        - 'use advanced search'
        - 'view own unpublished content'
    user.role.anonymous:
      grantPermissions:
        # We assume all published content should be accessible and searchable.
        - 'access content'
        - 'use advanced search'
    user.settings:
      simple_config_update:
        verify_mail: true
        register: admin_only
        cancel_method: user_cancel_block
